### ISSUE TITLE
BUG: Ember app not loading in IE11

### ISSUE THREAD

**Issue by obiwanus** [Matt-Jensen/ember-cli-g-maps#105] opened 2017-11-22 02:32 UTC
* Operating System version: Windows 7/10
  * Ember CLI version: 2.10.1
  * Ember CLI G Maps version: 0.5.1

It looks like as Google have updated their maps API, apps using ember-cli-g-maps stopped working in IE. **To reproduce**, look at your own demo page http://matt-jensen.github.io/ember-cli-g-maps/ in IE

No errors in IE console, no other hints. 

I've spent some time locating the problem, and apparently it fails just after it executes the script "//maps.googleapis.com/maps/api/js", so **it might very well be a problem with the maps api itself**. However, there's still a possibility that ember-cli-g-maps will have to do something to address the problem.

**Comment by Matt-Jensen** [comment] 2017-11-22 16:38
Attached is a screenshot on: Windows: 8.1, IE: 11 latest.  It was taken from a local ember development server, rather than the static production build seen on staging.

![image](https://user-images.githubusercontent.com/1538209/33138333-78b4bf02-cf67-11e7-8145-647e4e5b86d4.png)

Seems like there may be an issue with the documentation site, rather than the addon.  However if you're having issues with a prod build not working in IE 11, lets get you on the latest version of this project `0.5.14` and debug any errors from there.  Please reopen if you feel this was closed in error 😀

**Comment by obiwanus** [comment] 2017-11-22 17:17
Here's what I see (Windows 7):
![ember-cli-g-maps](https://user-images.githubusercontent.com/179863/33140775-d4a910fc-d015-11e7-8fe4-981486a74c60.png)

For my own project I've tried version `0.5.14`, and it didn't help either.

**Comment by Matt-Jensen** [comment] 2017-11-22 17:53
@obiwanus we both agree the documentation site does not load in IE 11.  This isn't strictly related to this addon, as the entire Ember app won't load on IE 11. I see the same thing as you do, however TBH I have no plans on fixing that particular _documentation issue_.

> For my own project I've tried version 0.5.14, and it didn't help either.

I'm not able to reproduce your issue, as that screenshot I took above was taken from an IE 11 browser.  Can you possibly reopen this issue with a link to reproducible code.

**Closed by Matt-Jensen** 2017-11-22 17:53 UTC

**Comment by obiwanus** [comment] 2017-11-22 17:58
Ah sorry I wasn't sure what you were referring to as the documentation site. Yes it's quite likely that this addon won't have anything to do with that issue. It is still an issue, however. I'm going to create a minimal test project that reproduces the bug. Will post an update here if I learn anything new
